# Generated by Django 5.2.7 on 2025-10-31 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0004_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='password_reset_token',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='Token đặt lại mật khẩu'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='password_reset_token_created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Thời gian tạo token đặt lại mật khẩu'),
        ),
    ]
