# Generated by Django 5.2.7 on 2025-10-31 16:20

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0005_userprofile_password_reset_token_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Tên tag')),
                ('color', models.CharField(default='#6c757d', help_text='Màu hex (e.g., #007bff)', max_length=7, verbose_name='Màu')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'task_tags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Tên dự án')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('goals', models.TextField(blank=True, help_text='Các mục tiêu của dự án', verbose_name='Mục tiêu')),
                ('status', models.CharField(choices=[('planning', 'Đang lên kế hoạch'), ('active', 'Đang thực hiện'), ('on_hold', 'Tạm dừng'), ('completed', 'Hoàn thành'), ('cancelled', 'Đã hủy')], default='planning', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Thấp'), ('medium', 'Trung bình'), ('high', 'Cao'), ('urgent', 'Khẩn cấp')], default='medium', max_length=20)),
                ('start_date', models.DateField(verbose_name='Ngày bắt đầu')),
                ('deadline', models.DateField(verbose_name='Hạn chót')),
                ('completion_percentage', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Phần trăm hoàn thành')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='led_projects', to=settings.AUTH_USER_MODEL, verbose_name='Trưởng nhóm')),
            ],
            options={
                'db_table': 'projects',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('leader', 'Trưởng nhóm'), ('developer', 'Lập trình viên'), ('designer', 'Thiết kế'), ('tester', 'Kiểm thử'), ('analyst', 'Phân tích'), ('member', 'Thành viên')], default='member', max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetings.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'project_memberships',
            },
        ),
        migrations.AddField(
            model_name='project',
            name='members',
            field=models.ManyToManyField(related_name='projects', through='meetings.ProjectMembership', to=settings.AUTH_USER_MODEL, verbose_name='Thành viên'),
        ),
        migrations.CreateModel(
            name='ProjectProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_tasks', models.IntegerField(default=0)),
                ('completed_tasks', models.IntegerField(default=0)),
                ('overdue_tasks', models.IntegerField(default=0)),
                ('completion_percentage', models.IntegerField(default=0)),
                ('tasks_completed_last_week', models.IntegerField(default=0)),
                ('snapshot_date', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_snapshots', to='meetings.project', verbose_name='Dự án')),
            ],
            options={
                'db_table': 'project_progress',
                'ordering': ['-snapshot_date'],
            },
        ),
        migrations.CreateModel(
            name='TodoTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Tiêu đề')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('status', models.CharField(choices=[('todo', 'Cần làm'), ('in_progress', 'Đang làm'), ('review', 'Đang review'), ('completed', 'Hoàn thành'), ('cancelled', 'Đã hủy')], default='todo', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Thấp'), ('medium', 'Trung bình'), ('high', 'Cao'), ('urgent', 'Khẩn cấp')], default='medium', max_length=20)),
                ('due_date', models.DateField(verbose_name='Hạn chót')),
                ('estimated_hours', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Ước tính giờ')),
                ('actual_hours', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Giờ thực tế')),
                ('progress_percentage', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Phần trăm hoàn thành')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assignees', models.ManyToManyField(blank=True, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Người thực hiện')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='meetings.project', verbose_name='Dự án')),
                ('tags', models.ManyToManyField(blank=True, related_name='tasks', to='meetings.tasktag', verbose_name='Tags')),
            ],
            options={
                'db_table': 'todo_tasks',
                'ordering': ['-priority', 'due_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('created', 'Tạo mới'), ('status_changed', 'Thay đổi trạng thái'), ('assigned', 'Gán người thực hiện'), ('priority_changed', 'Thay đổi ưu tiên'), ('updated', 'Cập nhật'), ('commented', 'Bình luận')], max_length=20)),
                ('old_value', models.TextField(blank=True, verbose_name='Giá trị cũ')),
                ('new_value', models.TextField(blank=True, verbose_name='Giá trị mới')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Người thực hiện')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='meetings.todotask', verbose_name='Task')),
            ],
            options={
                'db_table': 'task_history',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField(verbose_name='Nội dung')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Người bình luận')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='meetings.todotask', verbose_name='Task')),
            ],
            options={
                'db_table': 'task_comments',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='projectmembership',
            index=models.Index(fields=['project', 'user'], name='project_mem_project_78fd07_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='projectmembership',
            unique_together={('project', 'user')},
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['leader', 'status'], name='projects_leader__96a44b_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['status', 'deadline'], name='projects_status_bc54d4_idx'),
        ),
        migrations.AddIndex(
            model_name='projectprogress',
            index=models.Index(fields=['project', '-snapshot_date'], name='project_pro_project_099590_idx'),
        ),
        migrations.AddIndex(
            model_name='todotask',
            index=models.Index(fields=['project', 'status'], name='todo_tasks_project_b75e0b_idx'),
        ),
        migrations.AddIndex(
            model_name='todotask',
            index=models.Index(fields=['status', 'due_date'], name='todo_tasks_status_3d7daf_idx'),
        ),
        migrations.AddIndex(
            model_name='todotask',
            index=models.Index(fields=['priority', 'due_date'], name='todo_tasks_priorit_194b21_idx'),
        ),
        migrations.AddIndex(
            model_name='taskhistory',
            index=models.Index(fields=['task', '-created_at'], name='task_histor_task_id_bd5439_idx'),
        ),
        migrations.AddIndex(
            model_name='taskhistory',
            index=models.Index(fields=['action', '-created_at'], name='task_histor_action_7beb09_idx'),
        ),
        migrations.AddIndex(
            model_name='taskcomment',
            index=models.Index(fields=['task', 'created_at'], name='task_commen_task_id_413a08_idx'),
        ),
    ]
